/* eslint-disable */
// Generated by Wrangler by running `wrangler types functions/worker-configuration.d.ts --include-runtime=false` (hash: 60e7f17e896076f92640fc87f57c4b9b)
declare namespace Cloudflare {
	interface Env {
		CONTRACT_SHARES: KVNamespace;
	}
}
interface Env extends Cloudflare.Env {}

